### ISSUE TITLE
Information Store Security Schema across i2 Connect connectors.

### ISSUE THREAD

**Issue by logicalis-i2** [i2group/analyze-connect#13]
Hello,
We have successfully developped several i2 Connect connectors (in fact the end user did), everyone accessing to the external database with a generic user/pwd (hard set during the deploy of the connector), and so only returning the data that that user/pwd can access in that external database.
We have set the LDAP configuration to login to the information store with its Security Schema, but the i2 connect  connectors still use the generic user/pwd to get the info from each external database.

>> So, hows does the security schema apply, or is passed, to an external connector?

The idea is that if I login to ANB-Premium (Information Store) as User1, the i2 connect connector used passes user1 to the external database connection, returning only information that user1 is allowed to see, mapped to the IS Security Schema for User1.
In fact applying the security schema and the logged user to Iformation Store and connectors all together, all around.

Thanks for helping us with that.
Luis.

**Comment by Anthony-Johnson-i2** [comment]
Hi Luis

The issue here seems to be the fact that everyone accesses the external systems with a generic user/pwd (hard set during the deploy of the connector) when what you ideally want to do is to be able access the external system with rights in that system based on who has actually signed  in from the client side.

Providing such information to the connector is possible and is described here:

https://i2group.github.io/analyze-connect/content/example-connectors/user-configuration.html

https://i2group.github.io/analyze-connect/content/miscellaneous/principal-propagation.html

Hope this helps.

Cheers

**Comment by Anthony-Johnson-i2** [comment]
@Afira-Zahari-i2  Thank you for the clarification Afira.

**Comment by logicalis-i2** [comment]
Hello.
Ok. Interesting! and we think we understand that part, but we have an issue, or it might be a "mind blockage"! :) that doesn't let us understand something. I will try to explain.

In our implementation the way of ingesting data to the I.S. is made exclusively through connectors, accessing several external Databases.
Once the info is on the chart, we decide to upload it all (or part) to I.S. or not.

-> We are implementing LDAP so that users logged in ANB-P will be passed to the connector(s), and if I understand well, together with the security dimensions for that user, so that when the info will return from the connector to the chart, it will do it with those security dimensions "stamped" on them. Ready to be uploaded to IS. (correct?).
-> The idea of passing to the connector(s) the user (LDAP one) is to restrict in the "connected" database the queries (and else), as we suppose the 'external Database' security will apply to that user, as defined within that external database.
Doubts:
- If we access as UserHIGH, that in the 'external Database' can see any data (everything), and the info is returned "stamped" with a i2 security Dimension ALPHA, and uploaded to the IS.
- Now If we access to the ANB-P (I.S.) as UserLOW that in the 'external Database' can only see some data, and in i2 I.S. he can only see info "stamped" with a i2 security Dimension BETA. What will happen is that the info (some) that UserLOW is allowed to see in the external database, he won't be able to see it in i2 I.S. because it has been uploaded to the I.S. with an ALPHA stamp (by userHIGH).
If the security "scheme" in the external database(s) was identical to the one in i2, it was ok, just passing the dimension values as is, but they are not.
Any idea to overcome this?

Thanks very much for any idea and help on that.

**Comment by Anthony-Johnson-i2** [comment]
Hi 

I understand what you are saying and you have understood  exactly how this is working so you have no 'mind blockage'  :-)

The basic issue is that you want what a user can see and retrieve from the external system to be controlled by that external system recognising the user and giving appropriate access based on the external system security rules and access restrictions relating to the data for that user. That is easily done as we have described. 

However, you want the  data that is retrieved to have its access restrictions in our system based on how that data was categorized in the external system not who retrieved it.

Unfortunately, currently, it is not possible to set the security on retrieved items  according to  information about their security classifications in the  external data stores.

Requests to i2 Connect connectors do contain the user security as you have seen, so that can also  be used to control what data they are allowed to lookup from the external database (assuming they are able to map the security values from i2 Analyze to whatever scheme they are using in the DB).

**Responses from i2 Connect do not contain any security dimensions - records are returned without security.** 

ANBP applies "default" security to records, as they are added to the chart. What security is applied is configurable - either across the application for all users, or can even be configured, programmatically, to set security on records according to who the user is as you have seen. 

I think that what you are wanting is exactly how I would want to be able to do this and I would suggest that you raise an enhancement request for this functionality.

I will also separately contact our product manager   to let them know what you are asking for as I expect others will want  this functionality as well.

Cheers

**Comment by logicalis-i2** [comment]
Good morning Tony.
Thanks very much for the valuable information!

In fact, I’ve had a conversation with the customer (we should have had that one earlier! But we didn’t want to alarm him) and seems we have the problem solved!!
The customer itself thought about that problem, so what they are doing right now is replicating the i2 dimensions to all the external databases! So once connected, passing the correct user to the external database through the connector, and so filtering the info for that user/group, we just need to transfer the corresponding dimension values to the info back to i2.
This should do the trick.

Thanks very much Tony for your help!!
Best regards.
Luis.


De: Tony Johnson ***@***.***>
Enviado el: jueves, 19 de mayo de 2022 10:39
Para: i2group/analyze-connect ***@***.***>
CC: logicalis-i2 ***@***.***>; Author ***@***.***>
Asunto: Re: [i2group/analyze-connect] Information Store Security Schema across i2 Connect connectors. (Issue #13)


Hi

I understand what you are saying and you have understood exactly how this is working so you have no 'mind blockage' :-)

The basic issue is that you want what a user can see and retrieve from the external system to be controlled by that external system recognising the user and giving appropriate access based on the external system security rules and access restrictions relating to the data for that user. That is easily done as we have described.

However, you want the data that is retrieved to have its access restrictions in our system based on how that data was categorized in the external system not who retrieved it.

Unfortunately, currently, it is not possible to set the security on retrieved items according to information about their security classifications in the external data stores.

Requests to i2 Connect connectors do contain the user security as you have seen, so that can also be used to control what data they are allowed to lookup from the external database (assuming they are able to map the security values from i2 Analyze to whatever scheme they are using in the DB).

Responses from i2 Connect do not contain any security dimensions - records are returned without security.

ANBP applies "default" security to records, as they are added to the chart. What security is applied is configurable - either across the application for all users, or can even be configured, programmatically, to set security on records according to who the user is as you have seen.

I think that what you are wanting is exactly how I would want to be able to do this and I would suggest that you raise an enhancement request for this functionality.

I will also separately contact our product manager to let them know what you are asking for as I expect others will want this functionality as well.

Cheers

**Comment by Anthony-Johnson-i2** [comment]
@logicalis-i2 

Hi Luis

I think that  aligning the external security  certainly helps  to ensure consistency between what a user has access to within our system and within the external systems,  but you will not be able to assign security dimension values  and return them with the returned record data on a record by record basis.

ANBP can, as mentioned above, apply the same security to all results retrieved but even if you knew that  some needed ALPHA security to be applied and some needed BETA security to be applied there is currently no way to do that other than manually altering that in the Record Inspector once they were charted.

**Comment by logicalis-i2** [comment]
Ok. Understood.
We will have a deeper look then to your comments and see with my colleagues and customer, how we can proceed.
Thanks Very much!


De: Tony Johnson ***@***.***>
Enviado el: jueves, 19 de mayo de 2022 12:06
Para: i2group/analyze-connect ***@***.***>
CC: logicalis-i2 ***@***.***>; Mention ***@***.***>
Asunto: Re: [i2group/analyze-connect] Information Store Security Schema across i2 Connect connectors. (Issue #13)


@logicalis-i2<https://github.com/logicalis-i2>

Hi Luis

I think that aligning the external security certainly helps to ensure consistency between what a user has access to within our system and within the external systems, but you will not be able to assign security dimension values and return them with the returned record data on a record by record basis.

ANBP can, as mentioned above, apply the same security to all results retrieved but even if you knew that some needed ALPHA security to be applied and some needed BETA security to be applied there is currently no way to do that other than manually altering that in the Record Inspector once they were charted.

**Comment by Anthony-Johnson-i2** [comment]
Hi Luis 

I am closing this issue now as we have discussed the current limitations and that what you were wanting to do  to do is beyond what is currently available. 

I have emailed the development and product managers suggesting that we should look at allowing records to be returned from i2 Connect with individually assigned security values.

Please feel free to raise your own enhancement request for this as well.

Cheers
