### ISSUE TITLE
Analyst's Notebook identity of entities

### ISSUE THREAD

**Issue by RafaelCastilhoCastro** [i2group/analyze-connect#22]
Hi team,
We need to configure our connector so that the entities have an Analyst's Notebook identity when they are displayed on the chart. For now entities possess only a database identity and the Analyst's Notebook identity field remains blank. According to the documentation the configuration of the connection to the data source defines if this field stays blank. We couldn't find the instructions for this configuration though. Can you please help us on how to do it or where to find the instructions?

Thank for the support.

**Comment by Elizaveta-Golova-i2** [comment]
Hi Rafael,
With an i2Analyze deployment, database keys (in the "Database Identity" field) act as identifiers and the "Identity" field is not used and thus is not populated.
What exactly are you trying to do?

**Comment by Elizaveta-Golova-i2** [comment]
You can not set the Identity field for a record in ANB as it is for non i2Analyze deployments and is not used.

ANB is duplicating those entities because they are being added to the chart with different source identifiers, so ANB believes those records to be different.
If you have the same records from different sources, you have to ensure that you generate the same source identifiers for them, so as to indicate to ANB that the records are the same. 
Sounds like in your case you wouldn't be able to use the original source as a key for your source identifiers but will have to use some other combination of record distinguishing fields. 

Have a look at [source identifiers](https://i2group.github.io/analyze-connect/content/miscellaneous/source-identifiers.html), specifically the [Build a Source Identifier](https://i2group.github.io/analyze-connect/content/miscellaneous/source-identifiers.html#build-a-source-identifier) tutorial section. This includes some example code.

**Comment by RafaelCastilhoCastro** [comment]
We looked into the content about source identifiers as you suggested and it doesn't look like it will solve our issue.
Let me explain a little more what we're doing using an example.
First we import some data from a xls spreadsheet while setting a specific column as its identity. ANB will then fill the entity's identity field with that data.

![1](https://github.com/i2group/analyze-connect/assets/65736872/07f98650-183a-4034-afd7-bc989c9f9baf)

![WhatsApp Image 2023-08-04 at 13 14 38](https://github.com/i2group/analyze-connect/assets/65736872/7404c625-aa7b-4142-97d2-a6422091f6ed)

Then we add the same entity using our connector. In this case the Identity field is blank and duplicity happens. 

![WhatsApp Image 2023-08-04 at 13 15 42](https://github.com/i2group/analyze-connect/assets/65736872/381bcdc0-753d-41ad-9626-7ce30169dc25)

Let's say we set source identifiers on our connector. We'll face the same problem, right? The data coming from a spreadsheet for example won't match the source identifiers.

We understand were able to solve this issue before (when using our ANB plugin) by populating the entities' Identity field. Now we're using a connector and we thought we could do the same. Can you confirm it is not possible to set the Identity field when importing data through a connector to work this issue?

Thank you for the support.

**Comment by Andrew-Stawarz-i2** [comment]
I presume the scenario is "I have charted some items from an i2 Connect external search and now wish to ad-hoc import from a text/Excel file and have those imported items match-up with any previously charted from i2 Connect"?

As you may already be aware when using i2 Analyst's Notebook Premium (ANBP) we try and operate in a record centric way unlike in classic i2 Analyst's Notebook (ANB) where you are creating chart items with chart item properties attributes and cards along with simple chart item identity.

So the first step is to no longer make use of "classic" import specifications (*.ximp) in ANBP but start creating premium import specifications (*.oimp) to create records on the chart that align with the schema/s used in i2 Connect's external searches.

<img width="437" alt="image" src="https://github.com/i2group/analyze-connect/assets/97096500/6dcff869-100c-4637-bd06-be8aaac78d7f">

The workflow with the two types of specifications are generally the same until you get to the "Assign Columns" page whereby you will be constrained to the i2 Connect schema types and their properties when creating mappings between columns in the data and a property.

When the import is executed chat items with records will be created in the target chart, however those records will have a "unique" i2Analyze record identifier along with no source identifiers (no means to specify these in the ANBP importer). So how can you get imported records to match what is already on the chart? There are two means to do this.

1. The i2 Connect admin can create "system match rules" that define what combination of properties on a records should be considered to see if records are a match. Once the rules have been deployed the user can specify this means of matching in the import specification.
2. Or, the user can specify matching properties for an item type in the import specification directly. 

<img width="737" alt="image" src="https://github.com/i2group/analyze-connect/assets/97096500/7c35b5b8-45b7-4cb2-a928-6f76f3572e34">

Through either of these methods, during import ANBP will try an identify matching items and update anything found on the chart that matches with the incoming data from the import (if configured to merge) or place the records in the chart chart item (if configured to unite).

However you mention you already have a "strong" identifier. Maybe you could change your i2 Connect schema to include that as a property on the chart item, so that identifier will appear on records for i2 Connect searches, and, you will then be able to make use of it in the import specification to link to a column in your data fle and use that for item matching either by system rules or item matching constraints in the import specification.

**Comment by Anthony-Johnson-i2** [comment]
Hi @RafaelCastilhoCastro 

I see that there has been no response on this issue since @Andrew-Stawarz-i2  replied on 7 August. 

Are you happy for this issue to be closed given the support you have had from Andrew and Elizaveta?

**Comment by chriiisiscoding** [comment]
If I may add to this thread. I had an issue that seems, if not the same, very related to this. I return entities from the same source and the entities have the same identifier. But when click on "add to chart" with the same exact entity selected in the search result, the entity will be duplicated every time:

![image](https://github.com/i2group/analyze-connect/assets/15349825/e6fea9f6-487b-43ed-a005-506cec51dee9)

Clearly, the entities all have the same entity ID. Why would it be duplicated? In contrast, we don't have that issue when repeatedly adding entities that come from the InfoStore.

**Comment by Anthony-Johnson-i2** [comment]
Hi Chris 
Thank you for your input to this issue.

The problem here is slightly different from yours (as you have noted) as Rafael is trying to get entitles from different sources to not show as duplicates by assigning the same chart Item Identity to them and development have  responded saying 

_With an i2Analyze deployment, database keys (in the "Database Identity" field) act as identifiers and the "Identity" field is not used and thus is not populated._

You say that clearly the entities all have the same entity ID... 

For  two entities to be 'the same'  and not duplicated on the chart when coming from the same external source, they should have the same result id's and you need to have specified for your connector that those result id's are persistent. This is described for analyze-connect as part of [Implementing config](https://i2group.github.io/analyze-connect/content/workflow/config.html?q=resultIdsPersistent) and has been highlighted in the link given.

This is also discussed for its analyze-connect-node-sdk  alternative  in the linked issue
[Option "hasPersistentResultIds" not working](https://github.com/i2group/analyze-connect-node-sdk/issues/2) in case you are using that.

Cheers

**Comment by Colvin-Cowie-i2** [comment]
In addition to the [resultIdsPersistent](https://i2group.github.io/analyze-connect/content/workflow/config.html?q=resultIdsPersistent) option, the newer option is to use [source identifiers](https://i2group.github.io/analyze-connect/content/miscellaneous/source-identifiers.html) as the ids of your records. Source Identifiers are the better option if you have meaningful identifiers for the data you return, as they will be recognizable throughout the system, including on seeds.

**Comment by Anthony-Johnson-i2** [comment]
Thanks Colvin.

**Comment by chriiisiscoding** [comment]
Thanks for all the great input! That's definitely helped me look in the right places. Unfortunately, I still haven't resolved my issue.

First up I should mention that I don't use the SDK but just a modified version of the NYPD Python connector.

I have had set the `resultIdsPersistent` to `true` in the `defaultValues` field of the config. I now also set it for the specific service I'm testing (just to make double sure). It still creates duplicated entities.

I also tried to set `"clientConfigType": "NONE"` as suggested in the documentation for SPI versions 1.0 and 1.1 (frankly, don't understand what SPI version to specify but that's a different question). However, setting this seems to cause more serious issues. When I clicked on the folder icon for my query, it wouldn't load the search form at all but run an empty query right away. I'm not sure what the problem was there. So I took that out.

Finally, I also changed the id of the entity to match the source identifier format. Below is an example of an entity that would be returned:

```json
{
  "id": {
    "sourceId": {
      "type": "APP",
      "key": [
        "APP",
        "ET5:50fcfbf5f69e7b51b991be89f608b8ef"
      ]
    }
  },
  "properties": {"PT1":"John Doe"},
  "sourceReference": {
    "source": {
      "description": "APP Data",
      "name": "APP",
      "type": "Customer Data"
    }
  },
  "typeId": "ET5"
}
```

That also didn't solve the problem. There is something curious that I just noticed and that is this label that now appears with the entity:

<img width="168" alt="image" src="https://github.com/i2group/analyze-connect/assets/15349825/eadd97e7-a1b0-4f6c-a2e3-f4948a82aea1">

I hadn't noticed that before and I'm suspecting it is due to some of the changes I just made. Perhaps that give you a clue why things are not working?

**Comment by Colvin-Cowie-i2** [comment]
Hi @chriiisiscoding , did you reload your gateway after making the changes to your configuration to set `resultIdsPersistent`? If you still aren't making progress, please open a separate issue.

Just to answer these two points:

> I also tried to set "clientConfigType": "NONE" as suggested in the documentation for SPI versions 1.0 and 1.1 (frankly, don't understand what SPI version to specify but that's a different question). However, setting this seems to cause more serious issues. When I clicked on the folder icon for my query, it wouldn't load the search form at all but run an empty query right away. I'm not sure what the problem was there. So I took that out.

That is something specific to that example service (a service which doesn't have a form), it's not related to the `resultIdsPersistent` setting., though I see why it was misleading.

> that also didn't solve the problem. There is something curious that I just noticed and that is this label that now appears with the entity: 
> <img width="168" alt="image" src="https://github.com/i2group/analyze-connect/assets/15349825/eadd97e7-a1b0-4f6c-a2e3-f4948a82aea1">
> I hadn't noticed that before and I'm suspecting it is due to some of the changes I just made. Perhaps that give you a clue why things are not working?

That relates to [item type mapping](https://docs.i2group.com/analyze/4.4.2/item-type-mapping-config.html) where types from the connector schema are mapped to types in an Information Store schema so that they can be [uploaded to the Information Store](https://docs.i2group.com/anb/9.4.1/info_store_uploading.html).
