### ISSUE TITLE
Visual queries via Python connector

### ISSUE THREAD

**Issue by chriiisiscoding** [i2group/analyze-connect#32]
With the latest release of i2 Analyze, we should now be able to support visual queries via connectors. We have developed a large Python-based connector and would like to add support for visual queries. However, the only information we could find about visual queries and connectors is is in the [context of the Node SDK](https://i2group.github.io/analyze-connect-node-sdk/guide/visual-query.html). But it is also rather sparse on the details of how to actually operate the connector to refresh results, etc.

Can you point me to an example on how to add a visual query to a Python based connector similar to the [NYPD example connector](https://i2group.github.io/analyze-connect-node-sdk/guide/visual-query.html)?

**Comment by Anthony-Johnson-i2** [comment]
Hi @chriiisiscoding  

We do have the [Rest SPI documentation](https://i2group.github.io/analyze-connect/content/rest/i2-connect-spi.html#overview) which includes what you need for VQ including descriptions.


![image](https://github.com/i2group/analyze-connect/assets/98407720/7e9d8e96-d5db-44e9-9565-9a571db7be48)

But it there is not an equivalent of [this page ](https://i2group.github.io/analyze-connect-node-sdk/guide/visual-query.html) and no Python based example as you say that I can find.

I will ask development and see what they say on the matter.

Cheers

**Comment by Ricardo-Antunes-i2** [comment]
Hi @chriiisiscoding,

As @Anthony-Johnson-i2 has pointed out, we do have the i2 Connect SPI that surfaces the visual query transport sent to connectors. The SPI does explain what the different Visual query models do. 

Unfortunately, we do not have an example in analyze-connect that demonstrates how to execute a Visual Query from a connector. As you can imagine visual queries have a lot of flexibility and can get complicated, not to mention that you could implement it on any data source you want. Depending on the shape of the visual query and the data source technology used by the connector code could look very different, hence the difficulty in creating a representative example.

**Comment by Anthony-Johnson-i2** [comment]
Thanks for the quick response @Ricardo-Antunes-i2

**Comment by chriiisiscoding** [comment]
Thank you for the pointers! That's definitely valuable information. I'm still struggling to figure out how to even get started. Could you just give me a very basic outline of what configurations I have to update where? I.e., do I add the configuration from the link above to my `config.json`? Do I add it to the `topology.xml` somehow? I also must admit that I haven't configured normal visual queries so perhaps there is a good page that explains that, which is applicable to the connector scenario?

**Comment by Ricardo-Antunes-i2** [comment]
You can configure the type of connector you want to create via the ClientConfig object by specifying that the _type_ is VISUAL_QUERY, rather than FORM, or CUSTOM, within the [ConnectorConfig]( https://i2group.github.io/analyze-connect/content/rest/i2-connect-spi.html#cmp--schemas-connectorconfig). This can be done via the config.json if you use one.

Once you've done that you should constrain the connector to the type of visual queries it can handle, see  [ConnectorConfig](https://i2group.github.io/analyze-connect/content/rest/i2-connect-spi.html#cmp--schemas-connectorconfig), specifically: "operatorUsageRules", "constraints", and " paletteItemTypes"). For help on how to configure the constraints see: [Adding a new service](https://i2group.github.io/analyze-connect-node-sdk/guide/visual-query.html#adding-a-new-service) in the i2 Connect SDK documentation. The SDK documentation also points to some documentation on how to configure the VQ rules from an information store perspective, similar principals apply to the VQs on connectors. 

Once you have configured the connector add it to the topology and run the toolkit command to update your [connector configuration](https://i2group.github.io/analyze-connect/content/walkthrough/3-deploy-connector.html) as you would normally do. The gateway will the identify the connector as being a VQ connector and alert ANB. When you hit the external searches button you should be able to see the connector there.

When you have submitted your VQ the connector will receive a request with a [VisualQueryItem]( https://i2group.github.io/analyze-connect/content/rest/i2-connect-spi.html#cmp--schemas-visualqueryitem) model. You can then interpret the contents of that model and convert it into a query your dtaasource understands.

Hope this helps.

**Comment by chriiisiscoding** [comment]
Thanks again for the great explanation. I updated the `version` of my `config.json` to `1.3` so that is uses the latest SPI. That required me to do some cleanup to get rid of the warnings for deprecated fields. Once I did that and restarted the server, I was able to run visual queries through the connector (on a very basic level for now). 

One of the main features that our users hope to get with visual queries is the ability to get alerts when something changes. We do that currently against the InfoStore by saving the query and checking the box for receiving alerts. I don't see a save button for external visual queries. Is that not yet supported? If not, do you know if it will be supported in the near future?

**Comment by Ricardo-Antunes-i2** [comment]
Hi @chriiisiscoding, the ability to save external searches is not yet supported within the product. If you have support entitlement and would like to formally request it, you can raise a support [request](https://i2group.com/support-request) referencing this issue and it can be raised as a Request for Enhancement (RFE).

**Comment by chriiisiscoding** [comment]
Thank you for that info. And thank you for you outstanding help with this. With your help, I was able to stand up Visual Queries for my users. It is greatly appreciated. This can be closed.
