### ISSUE TITLE
Point of query origin

### ISSUE THREAD

**Issue by chriiisiscoding** [i2group/analyze-connect#33]
For security reasons, I must limit what data is being served to the ANB desktop client. Is there a way to see if a query originated from the ANB desktop client or the web client? I thought it might be in the request header somewhere but I couldn't find anything in the header or documentation about the header.

(*Sorry to create so many tickets at the same time.*)

**Comment by Colvin-Cowie-i2** [comment]
Hello, I'm afraid that information isn't currently available on the SPI.

Though technically you could implement a request modifier extension point on the i2 Analyze server to extract the User-Agent header and forward it, I would first examine the requirements here. Any request header information relating to the User-Agent is not verifiable, e.g. I can make a request from a browser and set the User-Agent to `toaster`.

So the User-Agent shouldn't be depended upon for a _security_ concern, but it's okay for optimizations and tailoring an experience. Can you clarify the requirement and the intention of it?

For security concerns, it's more appropriate to make decisions based on the permissions of the User themselves, rather than the client they are using. This information is available on the SPI: https://i2group.github.io/analyze-connect/content/example-connectors/user-configuration.html (when the server is configured to send these headers to the connector).

**Comment by chriiisiscoding** [comment]
Thank you! Yes, we are already using the user name to filter documents. Unfortunately, I can't go into details about the security concerns but your guidance is already very helpful. Thank you!

**Comment by Anthony-Johnson-i2** [comment]
Hi @chriiisiscoding  are you happy for this to be closed now?

**Comment by chriiisiscoding** [comment]
Yes. Thank you for your help!
