### ISSUE TITLE
Result from connector ok but does not draw the results on the i2 chart.

### ISSUE THREAD

**Issue by logicalis-i2** [i2group/analyze-connect#4]
Hello everyone.
We have an issue with a connector that launches a seeded search:
That same seeded search does work in our demo environment (with a schema slightly different). We replicated the connector to a different environment (the schema is similar but probably with different item types and so with different type IDs- we are being carefull with that, and in fact double checking right now).

The search of an entity PERSON works. That entity becomes the seed:
We launch the seed search and we do get link data in the I2ConnectLinkData, with response /POST 200 (ok), but it is unable to paint the data into the chart.  
We get the follwing error:
"Failed to open the selected query. Contact your system administrator".

In the connector side, we can see all the parsed data, so the query is done and have succeeded in returning data.
What should we check?

I enclosed images with the code.
Many thanks for any help you can provide.
Luis.
![i2 Connect seeded search](https://user-images.githubusercontent.com/83452910/118134924-bab09100-b402-11eb-8430-cad5cf554679.png)

**Comment by TonyJon** [comment]
HI Luis

Can you let us know which version of i2 Analyze and Analyst's Notebook Premium are you using on your demo environment and on the machines you are now trying to use this on.

You can find the i2 Analyze version at the beginning of one of the log files stored in the toolkit/configuration/logs directory on each of your toolkits on the Liberty servers and the Analyst's Notebook Premium one is available in the  About information in that application accessed from its File menu. I expect they are the same on both systems but want to be sure as we have changed a fair amount to do with schemas and i2 Connect recently.

The troubleshooting guide offered as part of the GitHub resources here:

[https://ibm-i2.github.io/Analyze-Connect/content/miscellaneous/troubleshoot.html](url)


Has an entry for the issue you have reported,  so have a look at that information and in the log files it tell you about  and see if it can help you figure out what is going on here. 


You mention that the schema and ID's  used in each are a bit different so, as you say,  it is good to check that what you are referencing is still correct in the system you are now trying to use.

Thanks,
Tony

**Comment by aliciags** [comment]
Hello Tony, 

I am Luis associate, so I have checked the loggs and the error is the next one:

![image](https://user-images.githubusercontent.com/57096508/118474553-7cb9b280-b70b-11eb-8752-345839bab427.png)
 
The identifier of the entity is the unique id in the external source SQL database table. There is no other identifier, so how can the error be solved? 

Next, I am going to check the versions of i2 Analyze and Analyst's Notebook Premium.

Thank you, 
Alice

**Comment by TonyJon** [comment]
Hi Alice

What is doesn't like is that it thinks you are trying to send the same  record data more than once in the results you are returning because it has been given results where the Identifier `PER0000020RPG2`  appears more than once.

If you look in the data your connector returning to us  you will see this.

So it could be perhaps that you are using one of the end entity Identifier's as the Identifier for your relation link because in your external system an Identifier does not exist for the relationship itself? 

If you did that and your seed entity  was linked to several other entities  you might get that sort of problem.

What value are you supplying for `this.RelationTypeId` in your `createRelation` function?

If you do have unique identifiers for your relationships then it could just be that you are really incorrectly sending  end data for a relation more than once.

You can use a free application like  Fiddler to see the content of the communications that are coming back to your client machine and see what is actually being returned  if you have not already done that.


Cheers

**Comment by aliciags** [comment]
Hi again, 

The relation has its own identifier, but I am using the same id for the user entity id and the from end id field in the link. Could that be the problem?  Which value for the end id should be then? 

Thanks, 

Alicia

**Comment by TonyJon** [comment]
Hi Alicia

It is normal for the fromEndId and toEndId to match the identifiers of the  end entity records  that they link to.

The log is saying that more than 1 incoming record has the same identifier so it is not referring to these end identifiers in the link record but to the incoming record identifiers themselves.

When you are doing something like an expand your SQL might be returning the entity records that relate to the from and the to ends of the relations with every relation link.  If so it might  have included the person entity record  that is the seed entity for example several times.

Looking at the data that is returned in the expand results should show this if it is the case.

Cheers

Cheers

**Comment by Colvin-Cowie-i2** [comment]
I believe this issue has been resolved, but if not then feel free to reopen it @logicalis-i2 @aliciags
